name: 'coding standards'

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  coding-standards:
    name: 'coding standards'
    runs-on: 'ubuntu-22.04'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v4'

      - name: 'build the environment'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.3'
          coverage: 'xdebug'
        env:
          fail-fast: true

      - name: 'composer install'
        uses: 'ramsey/composer-install@v3'

      - name: 'run php-cs-fixer'
        run: 'vendor/bin/php-cs-fixer fix --no-interaction --allow-risky=yes --diff --verbose --dry-run'