name: 'static analysis'

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  static-analysis:
    name: 'static analysis'
    runs-on: 'ubuntu-22.04'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v4'

      - name: 'build the environment'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.3'
          coverage: 'xdebug'
        env:
          fail-fast: true

      - name: 'composer install'
        uses: 'ramsey/composer-install@v3'

      - name: 'run phpstan'
        run: 'vendor/bin/phpstan analyse --level=9 src tests'